const PDFDocument = require('pdfkit');
const fs = require('fs');

function generateScanPDF({ url, result, scanDate, filePath }) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const navy = '#0B2545';
    const teal = '#12877F';
    const riskColors = { 'LOW RISK': '#1E8E3E', 'MEDIUM RISK': '#E8A33D', 'HIGH RISK': '#D93025' };
    const riskColor = riskColors[result.verdict] || '#333333';

    // Letterhead
    doc.rect(0, 0, doc.page.width, 90).fill(navy);
    doc.fillColor('#ffffff').fontSize(22).font('Helvetica-Bold').text('CYMOR SCAM SHIELD', 40, 28);
    doc.fontSize(10).font('Helvetica').fillColor('#B8C4D9').text('Link & Website Risk Report', 40, 56);
    doc.fontSize(9).fillColor('#B8C4D9').text(`Generated: ${scanDate}`, 40, 72);

    let y = 110;

    // Scanned link box
    doc.roundedRect(40, y, doc.page.width - 80, 46, 4).fillAndStroke('#F2F5F9', '#D8E0EA');
    doc.fillColor(navy).fontSize(10).font('Helvetica-Bold').text('SCANNED LINK', 50, y + 8);
    doc.fillColor('#111111').fontSize(10).font('Helvetica').text(url, 50, y + 22, { width: doc.page.width - 100 });
    y += 66;

    // Verdict banner
    doc.roundedRect(40, y, doc.page.width - 80, 50, 4).fill(riskColor);
    doc.fillColor('#ffffff').fontSize(16).font('Helvetica-Bold').text(`${result.emoji}  ${result.verdict}  —  ${result.score}/100`, 50, y + 15);
    y += 72;

    // Checks table
    doc.fillColor(navy).fontSize(13).font('Helvetica-Bold').text('Detailed Checks', 40, y);
    y += 20;

    const colX = [40, 260, 400];
    const rowH = 24;

    doc.rect(40, y, doc.page.width - 80, rowH).fill(teal);
    doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold');
    doc.text('Check', colX[0] + 8, y + 7);
    doc.text('Result', colX[1] + 8, y + 7);
    doc.text('Status', colX[2] + 8, y + 7);
    y += rowH;

    result.checks.forEach((c, i) => {
      const bg = i % 2 === 0 ? '#F7F9FB' : '#EDF1F5';
      doc.rect(40, y, doc.page.width - 80, rowH).fill(bg);
      doc.fillColor('#111111').fontSize(9.5).font('Helvetica');
      doc.text(c.name, colX[0] + 8, y + 7, { width: 210 });
      doc.text(c.result, colX[1] + 8, y + 7, { width: 130 });
      const statusColor = c.status === 'pass' ? '#1E8E3E' : c.status === 'warn' ? '#E8A33D' : '#D93025';
      const statusLabel = c.status === 'pass' ? '✓ Pass' : c.status === 'warn' ? '⚠ Caution' : '✗ Fail';
      doc.fillColor(statusColor).font('Helvetica-Bold').text(statusLabel, colX[2] + 8, y + 7);
      y += rowH;
    });

    y += 24;

    // Reasons
    doc.fillColor(navy).fontSize(13).font('Helvetica-Bold').text('Why This Verdict — Full Breakdown', 40, y);
    y += 20;

    result.reasons.forEach((reason, i) => {
      if (y > doc.page.height - 100) { doc.addPage(); y = 40; }
      doc.fillColor(riskColor).fontSize(10).font('Helvetica-Bold').text(`${i + 1}.`, 40, y);
      doc.fillColor('#222222').font('Helvetica').fontSize(10).text(reason, 60, y, { width: doc.page.width - 100 });
      y = doc.y + 12;
    });

    doc.fontSize(8).fillColor('#888888').text(
      'Report generated by Cymor Scam Shield | Developed by Legendary Smiley Cymor',
      40, doc.page.height - 40, { width: doc.page.width - 80, align: 'center' }
    );

    doc.end();
    stream.on('finish', () => resolve(filePath));
    stream.on('error', reject);
  });
}

module.exports = { generateScanPDF };
